#! /usr/bin/env node

const http = require('http');
const express = require('express');
const path = require('path');

const repoBase = path.dirname(__dirname)

const agentApp = express();
const customerApp = express();

agentApp.use(express.static(`${repoBase}/agent-app`));
const agentAppServer = http.createServer(agentApp);

customerApp.use(express.static(`${repoBase}/customer-app`));
const customerAppServer = http.createServer(customerApp);

agentAppServer.listen(8080);
console.log('Agent Test App running: http://localhost:8080');
customerAppServer.listen(8081);
console.log('Customer Test App running: http://localhost:8081');
console.log('Press ^C to stop the servers')

